In [1]:
import numpy as np
from copy import deepcopy
import time

In [2]:
from IPython import display
display.clear_output(wait=True)

In [3]:
def get_new_cell_state(board, cell_address, cell_state):
    if cell_state == 1:
        if (count_neighbors(board, cell_address) <= 1) | (count_neighbors(board, cell_address) >= 4):
            new_cell_state = 0
        else:
            new_cell_state = 1

    if cell_state == 0:
        if count_neighbors(board, cell_address) == 3:
            new_cell_state = 1
        else:
            new_cell_state = 0
    return new_cell_state

In [4]:
def count_neighbors(board, cell_address):
    neighbs = 0
    try:
        neighbs += board[cell_address[0]-1][cell_address[1]-1]
    except:
        pass
    try:
        neighbs += board[cell_address[0]-1][cell_address[1]+0]
    except:
        pass
    try:
        neighbs += board[cell_address[0]-1][cell_address[1]+1]
    except:
        pass
    try:
        neighbs += board[cell_address[0]+0][cell_address[1]-1]
    except:
        pass
    try:
        neighbs += board[cell_address[0]+0][cell_address[1]+1]
    except:
        pass
    try:
        neighbs += board[cell_address[0]+1][cell_address[1]-1]
    except:
        pass
    try:
        neighbs += board[cell_address[0]+1][cell_address[1]+0]
    except:
        pass
    try:
        neighbs += board[cell_address[0]+1][cell_address[1]+1]
    except:
        pass

    return neighbs

In [5]:
def build_new_matrix(board):
    (b_height,b_width) = np.shape(board)
    new_board = deepcopy(board)#np.zeros((b_height,b_width),dtype='int')
    for row_idx in range(b_height):
        for col_idx in range(b_width):
            new_board[row_idx][col_idx] = get_new_cell_state(board, (row_idx, col_idx), board[row_idx][col_idx])
    
    return new_board


In [6]:
b_height = 25
b_width = 35
board = np.zeros((b_height,b_width),dtype='int')

r = 2
c = 6
board[0+r][1+c] = 1
board[1+r][2+c] = 1
board[2+r][0+c] = 1
board[2+r][1+c] = 1
board[2+r][2+c] = 1

r = 0
c = 21
board[0+r][1+c] = 1
board[1+r][0+c] = 1
board[2+r][0+c] = 1
board[2+r][1+c] = 1
board[2+r][2+c] = 1

for count in range(120):
    display.clear_output(wait=True)
    print('\nstate:', count)
    print(board)
    time.sleep(0.1)
    board = build_new_matrix(board)





state: 119
[[0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0

In [82]:
import numpy as np
from copy import deepcopy
import time
from IPython import display


def get_new_cell_state(board, cell_address, cell_state):
    if cell_state == 1:
        if (count_neighbors(board, cell_address) <= 1) | (count_neighbors(board, cell_address) >= 4):
            new_cell_state = 0
        else:
            new_cell_state = 1

    if cell_state == 0:
        if count_neighbors(board, cell_address) == 3:
            new_cell_state = 1
        else:
            new_cell_state = 0
    return new_cell_state


def count_neighbors(board, cell_address):
    neighbs = 0
    try:
        neighbs += board[cell_address[0]-1][cell_address[1]-1]
    except:
        pass
    try:
        neighbs += board[cell_address[0]-1][cell_address[1]+0]
    except:
        pass
    try:
        neighbs += board[cell_address[0]-1][cell_address[1]+1]
    except:
        pass
    try:
        neighbs += board[cell_address[0]+0][cell_address[1]-1]
    except:
        pass
    try:
        neighbs += board[cell_address[0]+0][cell_address[1]+1]
    except:
        pass
    try:
        neighbs += board[cell_address[0]+1][cell_address[1]-1]
    except:
        pass
    try:
        neighbs += board[cell_address[0]+1][cell_address[1]+0]
    except:
        pass
    try:
        neighbs += board[cell_address[0]+1][cell_address[1]+1]
    except:
        pass

    return neighbs


def build_new_matrix(board):
    (b_height,b_width) = np.shape(board)
    new_board = deepcopy(board)#np.zeros((b_height,b_width),dtype='int')
    for row_idx in range(b_height):
        for col_idx in range(b_width):
            new_board[row_idx][col_idx] = get_new_cell_state(board, (row_idx, col_idx), board[row_idx][col_idx])
    
    return new_board

##################################################

b_height = 25
b_width = 35
max_iterations = 120
board = np.zeros((b_height,b_width),dtype='int')


# build gliders at 2,6 and 0,21
r = 2
c = 6
board[0+r][1+c] = 1
board[1+r][2+c] = 1
board[2+r][0+c] = 1
board[2+r][1+c] = 1
board[2+r][2+c] = 1

r = 0
c = 21
board[0+r][1+c] = 1
board[1+r][0+c] = 1
board[2+r][0+c] = 1
board[2+r][1+c] = 1
board[2+r][2+c] = 1

for count in range(max_iterations):
    display.clear_output(wait=True)
    print('\nstate:', count)
    print(board)
    time.sleep(0.1)
    board = build_new_matrix(board)







state: 119
[[0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0